version: '3.9'

services:

 roach1:
   image: cockroachdb/cockroach:latest
   ports:
     - "26257:26257"
     - "8080:8080"
   environment:
    COCKROACH_DATABASE: auth_db
    COCKROACH_USER: auth_db_user
    COCKROACH_PASSWORD: auth_db_pass
   command: start --insecure --join=roach1,roach2,roach3
   volumes:
     - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"

 roach2:
   image: cockroachdb/cockroach:latest
   ports:
     - "26258:26257"
     - "8081:8080"
   environment:
    COCKROACH_DATABASE: auth_db
    COCKROACH_USER: auth_db_user
    COCKROACH_PASSWORD: auth_db_pass
   command: start --insecure --join=roach1,roach2,roach3
   volumes:
     - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"

 roach3:
   image: cockroachdb/cockroach:latest
   ports:
     - "26259:26257"
     - "8082:8080"
   environment:
    COCKROACH_DATABASE: auth_db
    COCKROACH_USER: auth_db_user
    COCKROACH_PASSWORD: auth_db_pass
   command: start --insecure --join=roach1,roach2,roach3
   volumes:
     - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"