version: "3.9"

services:

  mysql:
    hostname: mysql-auth-poc.local
    image: mysql:8-oracle
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s
    volumes:
      - ./prometheus/exporter.sql:/docker-entrypoint-initdb.d/exporter.sql
      - mysql-data:/var/lib/mysql
#    deploy:
#      resources:
#        limits:
#          cpus: ".02"
#          memory: "1G"
#        reservations:
#          cpus: ".02"
#          memory: "1G"

  auth-poc-1:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    links:
      - mysqld-exporter

  mysqld-exporter:
    image: prom/mysqld-exporter
    command:
      - --collect.info_schema.query_response_time
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:root_pass@(mysql:3306)/
    ports:
      - 9104:9104
    depends_on:
      - mysql
#
#  proxy:
#    image: nginx:latest
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      auth-poc-1:
#        condition: service_healthy


volumes:
  mysql-data: