version: "3.9"

services:

  mysql:
    hostname: mysql-auth-poc.local
    image: mysql:8-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s
    volumes:
      - ./prometheus/exporter.sql:/docker-entrypoint-initdb.d/exporter.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    links:
      - mysqld-exporter

  mysqld-exporter:
    image: prom/mysqld-exporter
    command:
      - --collect.info_schema.query_response_time
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporterpassword@(mysql:3306)/
    ports:
      - 9104:9104
    depends_on:
      - mysql