version: "3.9"

services:
  mysql:
    hostname: mysql-auth-poc.local
    image: mysql:8-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: auth_poc
      MYSQL_PASSWORD: auth_poc_pass
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: auth_poc