version: "3.9"

services:

  mysql:
    hostname: mysql-auth-poc.local
    image: mysql:8-oracle
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          cpus: ".02"
#          memory: "1G"
#        reservations:
#          cpus: ".02"
#          memory: "1G"

  auth-poc-1:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  auth-poc-2:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  auth-poc-3:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  auth-poc-4:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s


  auth-poc-5:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s


  auth-poc-6:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s


  auth-poc-7:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s


  auth-poc-8:
    image: ghcr.io/devaffeine/sb-auth-poc:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8080/actuator/health | grep UP"
        ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      auth-poc-1:
        condition: service_healthy
      auth-poc-2:
        condition: service_healthy
      auth-poc-3:
        condition: service_healthy
      auth-poc-4:
        condition: service_healthy
      auth-poc-5:
        condition: service_healthy
      auth-poc-6:
        condition: service_healthy
      auth-poc-7:
        condition: service_healthy
      auth-poc-8:
        condition: service_healthy