apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: usersdb
spec:
  secretName: usersdb-pwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2
  datadirVolumeClaimTemplate:
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi