apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app-dply
  labels:
    app: auth-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: global-auth
          image: global-auth-cockroachdb-cluster-registry.local:5000/global-auth-cockroachdb:latest
          ports:
            - containerPort: 8090
          env:
            - name: JWT_SECRET_KEY
              value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            - name: DB_HOSTNAME
              value: myroach-cockroachdb-public
            - name: DB_PORT
              value: "26257"
            - name: DB_NAME
              value: defaultdb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: ""
          resources:
            limits:
              cpu: "1"
              memory: "1G"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-svc
  labels:
    app: auth-app-svc
spec:
  type: LoadBalancer
  selector:
    app: auth-app
  ports:
    - port: 8090
      targetPort: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-app-svc
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: auth-app-svc
                port:
                  number: 8090