apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app-dply
  labels:
    app: auth-app
spec:
  replicas: 30
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: global-auth
          image: global-auth-cockroachdb-cluster-registry.local:5000/global-auth-cockroachdb:latest
          ports:
            - containerPort: 8090
          env:
            - name: JWT_SECRET_KEY
              value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            - name: DB_HOSTNAME
              value: myroach-cockroachdb-public
            - name: DB_PORT
              value: "26257"
            - name: DB_NAME
              value: defaultdb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: ""
          resources:
            limits:
              cpu: "1"
              memory: "1G"
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-svc
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
  labels:
    app: auth-app-svc
spec:
  type: LoadBalancer
  selector:
    app: auth-app
  ports:
    - port: 8090
      targetPort: 8090