# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dns" do |cfg|
    cfg.vm.box = "ubuntu/jammy64"
    cfg.vm.network "private_network", ip: "192.168.50.10"
    cfg.vm.synced_folder "./dns", "/etc/bind/"

    cfg.vm.provider "virtualbox" do |v|
      v.memory = 8192
      v.cpus = 4
      v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt install bind9 -y
    SHELL
  end

  # config.vm.define "s1" do |cfg|
  #   cfg.vm.box = "ubuntu/jammy64"
  #   cfg.vm.network "private_network", ip: "192.168.50.20"
  #   # config.vm.synced_folder "../data", "/vagrant_data"

  #   cfg.vm.provider "virtualbox" do |v|
  #     v.memory = 8192
  #     v.cpus = 4
  #     v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  #   end
  # end

  # config.vm.define "s2" do |cfg|
  #   cfg.vm.box = "ubuntu/jammy64"
  #   cfg.vm.network "private_network", ip: "192.168.50.21"
  #   # config.vm.synced_folder "../data", "/vagrant_data"

  #   cfg.vm.provider "virtualbox" do |v|
  #     v.memory = 8192
  #     v.cpus = 4
  #     v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  #   end
  # end
end
