name: Build
run-name: Build by ${{ github.actor }}
on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: build jibDockerBuild
      - name: Newman Tests
        run: |
          cp .env-sample .env
          docker compose -f docker-compose-tests.yml up postman
          docker compose -f docker-compose-tests.yml down
      - name: Publish Java Package
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: publish
      - name: Publish Docker Image
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.REGISTRY }}/devaffeine/sb-auth-poc:latest
